version: '3.5'
services:

  prometheus:
    image: prom/prometheus:v2.6.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
#    network_mode: 'host' # to test locally running service -> not for Mac OS

  grafana:
    image: grafana/grafana:9.2.15
    container_name: grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 3000:3000
#    network_mode: 'host' # to test locally running service -> not for Mac OS
