apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    # On MacOS, replace localhost by host.docker.internal
    # On Windows, replace 'host'
    url: http://host.docker.internal:9090
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser: admin
    basicAuthPassword: admin
    withCredentials:
    isDefault: true
    jsonData:
      graphiteVersion: '1.1'
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: '...'
      tlsClientCert: '...'
      tlsClientKey: '...'
    version: 1
    editable: true
